### ISSUE TITLE
When scriptingEnabled false and head contains noscript, $('body').text()/textContent/innerText returned is incorrect and includes head text

### ISSUE THREAD

**Issue by cmawhorter** [cheeriojs/cheerio#3050] opened 2023-03-12 07:47 UTC
I'm guessing this is a parse5 issue but I don't have the time to confirm atm.

In the following situation:
- scriptingEnabled: false
- Getting text content for $('body').text()/textContent/innerText
- `<head>` contains `<noscript>`

The text content returned will be relative to the noscript and include text from head i.e. noscript + everything after in head + body.

```js
const html = `
<!doctype html>
<html>
<head>
<script>alert('this is not the body')</script>
<noscript>document owner error</noscript>
<script>alert('this is still not the body')</script>
</head>
<body>
<p>this is the body</p>
</body>
</html>
`;
[false, true].forEach(scriptingEnabled => {
  console.log('scriptingEnabled', scriptingEnabled);
  console.log(new Array(55).join('='));
  const $ = cheerio.load(html, {scriptingEnabled});
  console.log('text()', {text: $('body').text() });
  console.log('textContent', {text: $('body').prop('textContent') });
  console.log('innerText', {text: $('body').prop('innerText') });
  console.log(new Array(55).join('='), '\n\n\n\n');
});
```

Results in:
```
scriptingEnabled false
======================================================
text() {
  text: 'document owner error\n' +
    "alert('this is still not the body')\n" +
    '\n' +
    '\n' +
    'this is the body\n' +
    '\n' +
    '\n'
}
textContent {
  text: 'document owner error\n' +
    "alert('this is still not the body')\n" +
    '\n' +
    '\n' +
    'this is the body\n' +
    '\n' +
    '\n'
}
innerText { text: 'document owner error\n\n\n\nthis is the body\n\n\n' }
====================================================== 




scriptingEnabled true
======================================================
text() { text: '\nthis is the body\n\n\n' }
textContent { text: '\nthis is the body\n\n\n' }
innerText { text: '\nthis is the body\n\n\n' }
====================================================== 
```

**Comment by fb55** [comment] 2023-03-12 13:53
This is an interesting oddity of the `<noscript>` tag: Text content can only be a part of the body of a document, so if scripting is disabled, the `<noscript>` contents lead an implicit `</head><body>` in the markup (the occurrence of this further down is ignored). With that, the `<script>` tag after it will be pushed to the body.

Hope that makes sense! Closing as this works as intended (even if surprising).

**Closed by fb55** 2023-03-12 13:53 UTC

**Comment by cmawhorter** [comment] 2023-03-12 22:09
i'm [not seeing anything in the spec](https://html.spec.whatwg.org/multipage/scripting.html#the-noscript-element) about the implied body. am i looking in the wrong section? 

that link does mention that noscript **is** allowed in head -- with scripting enabled or disabled -- as long as it only contains link/style/meta tags (which was news to me). 

FWIW chrome and presumably the other browsers do not behave this way with regard to body.textContent. that makes sense to me considering pasting a js snippet in head when it belongs in body is a common document author error.

**Comment by cmawhorter** [comment] 2023-03-15 15:23
this section 13.2.6.4.5 is the only section of this spec i've read, so it's definitely possible i'm interpreting it incorrectly, but my reading is:

- `<head>` -> "in head"
- `<noscript>` -> "in head noscript"
- `...</noscript>` -> "in head"

i don't see "after head" mentioned relating to the "in head noscript" mode. "in body" is mentioned, but only for an html tag nested under noscript.  i donno 🤷

**Comment by fb55** [comment] 2023-03-15 19:46
Look at the "Anything else" section at the bottom: The token will be re-parsed in `in-head` mode, where it will be in "Anything else" again, which leads it to be re-parsed in `in-body`.
