### ISSUE TITLE
Attribute lookup is incorrecly case sensitive

### ISSUE THREAD

**Issue by windhandel** [cheeriojs/cheerio#643] opened 2015-01-29 22:17 UTC
It appears that looking up attributes is case sensitive, which we can't ensure that the attributes themselves are the "correct" case.  This will cause a lot of issues with our HTML parsing potentially.

**Comment by jugglinmike** [comment] 2015-01-29 23:38
This is a duplicate of an existing issue (gh-581), so I'm going to close it. Thanks for the report!

**Closed by jugglinmike** 2015-01-29 23:38 UTC
