### ISSUE TITLE
css-select upgrade to 1.1.0 causing tests to fail

### ISSUE THREAD

**Issue by blondyn** [cheeriojs/cheerio#728] opened 2015-06-29 21:38 UTC
Hi, the change of css-select dependency is causing quite a few tests to fail. ( at least on my 2 osx systems) 29d38e32889417390ee682b4169d6f9eee5f9d14

**Comment by jugglinmike** [comment] 2015-06-29 21:47
Thanks for the report! [Our CI builds passed on that commit](https://travis-ci.org/cheeriojs/cheerio/builds/66485511), but [we're not currently testing in Node.js v0.12](https://github.com/cheeriojs/cheerio/blob/8ee743e89ee03f04bba971ade430490b079abdaf/.travis.yml#L2-L4). I confirmed locally, so it looks like this is specific to that version of the platform.

@fb55 I won't be able to look into this until tomorrow; in the mean time, do you have any idea what could be the problem?

**Comment by blondyn** [comment] 2015-06-30 08:52
Hi again. It seems that introduction of absolutize function in css-select is causing this. However I don't know the code well, might be something else. What is certain is that commit (fb55/css-select@0f0daad251094287a6223ba24467bf073dc2c0fe) is a cause for this fail.

Sorry if this is not appropriate place for reference issue from other library. I just though that cheerio might be feeding css-select api with some deprecated data.

**Comment by jugglinmike** [comment] 2015-07-04 00:16
Thanks! That looks to be a regression in CSSselect. I tried and failed to patch it, so I've settled for submitting a failing test case: https://github.com/fb55/css-select/pull/30 . Hopefully @fb55 will have better luck than I.

**Comment by fb55** [comment] 2015-07-04 23:40
Sorry for the late response. I still don't fully understand the error (haven't looked at the code in a while), for now just reverting 29d38e3 is probably the best choice.

**Comment by Delgan** [comment] 2015-11-22 19:44
Ok, so, I spent some hours trying to solve this issue, and while I almost reach the goal, something disturbs me.

I am not sure to fully understand the issue.

With reference to the unit test from  [PR #30](https://github.com/fb55/css-select/pull/30):
```javascript
"should query array elements directly when they have parents"

var dom = makeDom("<div id=foo><p>foo</p></div>")[0];
var ps = CSSselect("p", [dom]);
assert.deepEqual(CSSselect("p", ps), ps);
```

What happens here:
* Create the dom.
* Query the dom to get every `<p>` tag and store them into an array.
* Query this array to find `<p>` tag and then check it equals to the previous one found.

So, from an array `[ {p_tag} ]`, the query should return the same result `[ {p_tag} ]`... Why that?

Querying an array is equivalent to apply the query on each element, am I wrong?
Then, finding a `<p>` tag from a `<p>` tag might return `null` because only the children are queried and the element itself is not included into the search, it can not be added to the results.

So, `CSSselect("p", ps)` behavior seems correct, it should return `[]`.

Others factors make this issue and unit tests look weird to me:
* [jQuery behaves](http://jsfiddle.net/hdeuq3w3/) just like I said
* [There is another unit test](https://github.com/fb55/css-select/blob/master/test/qwery/index.js#L277) which states <i>"exclude self in match"</i>

I think the correct behavior for the two unit tests is to return `[]`. 
Then, the first one is failing but it can be fixed.
This means there was no regression in css-select, but the current issue just highlights a former incorrect behavior of `CSSselect()`.

Once again, I could be wrong. I am far from have as much knowledge as @fb55 and @jugglinmike about css-select, but I hope you can explain me some details. I want to contribute and help you to fix this problem.

**Comment by Gabilow** [comment] 2015-11-23 10:19
I spent some hours trying to fix this issue but I need help to fully understand what are the expected results.

Based on [the documentation](https://github.com/fb55/css-select#cssselectquery-elems-options) and [the PR #30](https://github.com/fb55/css-select/pull/30), what I understood is:
* If the context (`elems` or `options.context`) is a single element, the query should not include this element to the results.
* If the context is an array of elements, the query is applied to every element like if it was some kind of "root", and so these elements are included to the search.

This is why one of the unit test to demonstrate the regression is:
```javascript
var dom = makeDom("<div id=foo><p>foo</p></div>")[0];
var ps = CSSselect("p", [dom]);
assert.deepEqual(CSSselect("p", ps), ps); 
// ps is an array so querying for "p" should include the one previously matched
```

But then, it seems to me that [there is another unit test](https://github.com/fb55/css-select/blob/master/test/qwery/index.js#L277) which does not match this statement:
```javascript
expect(CSSselect('.order-matters', CSSselect('#order-matters', document))).to.have.length(4);
//should not include self in element-context queries
```

It looks like it is the opposite of what I said, because as `CSSselect()` returns an array, querying `.order-matters` should include the "root" and return `5` ([see HTML](https://github.com/fb55/css-select/blob/master/test/qwery/index.html#L78)), is not it?
However, it should be ok if the test was using `CSSselect('#order-matters', document)[0]`.

I know these unit tests come from the <i>qwery</i> library.
So [I tried it](http://jsfiddle.net/dvYmQ/2/) on the test intended to demonstrate regression, and it does not match, the result is an empty array. [The other test](http://jsfiddle.net/dvYmQ/5/) returns an array of length `4`.

It looks like expected behaviors of <i>css-select</i> and <i>qwery</i> are not the same, I think <i>qwery</i> does not differentiate array or single element context. This means there are some unit tests which are incompatible.

Once again, I am far from have has much knowledge than @fb55 and @jugglinmike about <i>css-select</i> and I may be wrong, but I hope you can help me to understand why these result looks inconsistent. Then I could continue trying to solve this problem.

**Comment by Delgan** [comment] 2015-11-23 10:20
I spent some hours trying to fix this issue but I need help to fully understand what are the expected results.

Based on [the documentation](https://github.com/fb55/css-select#cssselectquery-elems-options) and [the PR #30](https://github.com/fb55/css-select/pull/30), what I understood is:
* If the context (`elems` or `options.context`) is a single element, the query should not include this element to the results.
* If the context is an array of elements, the query is applied to every element like if it was some kind of "root", and so these elements are included to the search.

This is why one of the unit test to demonstrate the regression is:
```javascript
var dom = makeDom("<div id=foo><p>foo</p></div>")[0];
var ps = CSSselect("p", [dom]);
assert.deepEqual(CSSselect("p", ps), ps); 
// ps is an array so querying for "p" should include the one previously matched
```

But then, it seems to me that [there is another unit test](https://github.com/fb55/css-select/blob/master/test/qwery/index.js#L277) which does not match this statement:
```javascript
expect(CSSselect('.order-matters', CSSselect('#order-matters', document))).to.have.length(4);
//should not include self in element-context queries
```

It looks like it is the opposite of what I said, because as `CSSselect()` returns an array, querying `.order-matters` should include the "root" and return `5` ([see HTML](https://github.com/fb55/css-select/blob/master/test/qwery/index.html#L78)), is not it?
However, it should be ok if the test was using `CSSselect('#order-matters', document)[0]`.

I know these unit tests come from the <i>qwery</i> library.
So [I tried it](http://jsfiddle.net/dvYmQ/2/) on the test intended to demonstrate regression, and it does not match, the result is an empty array. [The other test](http://jsfiddle.net/dvYmQ/5/) returns an array of length `4`.

It looks like expected behaviors of <i>css-select</i> and <i>qwery</i> are not the same, I think <i>qwery</i> does not differentiate array or single element context. This means there are some unit tests which are incompatible.

Once again, I am far from have has much knowledge than @fb55 and @jugglinmike about <i>css-select</i> and I may be wrong, but I hope you can help me to understand why these result looks inconsistent. Then I could continue trying to solve this problem.

**Comment by fb55** [comment] 2015-11-23 12:32
@Delgan I believe you are right that the qwery test is wrong and I didn't realize that when adjusting the behavior accordingly. The test should be fixed to use the element, without a wrapping array.

**Comment by Delgan** [comment] 2015-11-23 12:41
@fb55 I am glad to hear that, because this means the current issue can be fixed easily. I will try to submit a push request tonight, thank you for your answer.

**Closed** 2015-11-24 00:09 UTC
Labels: css-select
