### ISSUE TITLE
$(undefined).prop('href') throws error

### ISSUE THREAD

**Issue by rla** [cheeriojs/cheerio#875] opened 2016-06-14 21:42 UTC
`$(undefined).prop('href')` throws:

```
TypeError: Cannot read property 'hasOwnProperty' of undefined.
```

With jQuery the same expression returns `undefined`.

Tested with Cheerio 0.20.0

**Comment by sotojuan** [comment] 2016-06-15 20:24
Seems like the problem is [here](https://github.com/cheeriojs/cheerio/blob/master/lib/api/attributes.js#L94)? Seems an easy fix.

**Comment by rla** [comment] 2016-06-17 12:05
@sotojuan, if you are interested in taking over then go ahead.

**Comment by elias-winberg** [comment] 2016-06-17 16:21
It should be relatively easy to fix, no? If `el` is `undefined` immediately return `undefined`. I'll try to create a pull request.

**Comment by Delgan** [comment] 2016-06-17 16:28
Is it related to https://github.com/cheeriojs/cheerio/issues/554 ?

**Comment by elias-winberg** [comment] 2016-06-17 16:51
Sort of, jQuery creates the element even if the attribute value is undefined, and cheerio doesn't.

**Comment by rla** [comment] 2016-06-18 15:48
I add some background info.

The bug might also be triggered when the selector does not match, like in the code:

```js
$('.not-exists').attr('href')
```

It was not enough to check that `$('.not-exists')` is truthy before calling `.attr()` method. $ is Cheerio here. I ported the code from code using querySelector that behaves way more logically than jQuery.

Looking through the current Cheerio tests, it does not seem to consider negative cases when some input is undefiend or null.

**Comment by elias-winberg** [comment] 2016-06-18 16:15
`.attr` seems to be working as expected though (only `.prop` throws an error if the selector is invalid). I think this is due to the fact that the [`.getProp`](https://github.com/cheeriojs/cheerio/blob/e7d18af05ff1d23f17d858590e2e1d299f7bdf75/lib/api/attributes.js#L93) function lacks this [line](https://github.com/cheeriojs/cheerio/blob/e7d18af05ff1d23f17d858590e2e1d299f7bdf75/lib/api/attributes.js#L31).

**Comment by fb55** [comment] 2016-07-04 18:19
Fixed in https://github.com/cheeriojs/cheerio/pull/880

**Closed** 2016-07-04 18:19 UTC
