### ISSUE TITLE
TypeError: data.replace is not a function on html();

### ISSUE THREAD

**Issue by gahabeen** [cheeriojs/cheerio#970] opened 2017-01-25 13:18 UTC
Hi,

Not really sure what's going wrong, here is a test case I've got failing:
``` javascript
let cheerio = require('cheerio');
let $ = cheerio.load(`<body><div id="example"> <a href=""> Some content</a> </div></body>`);
console.log($('body').find('#example').html());
```

And the returned error:
``` bash
C:\Users\[PROJECT FOLDER]\node_modules\entities\lib\encode.js:58
                                .replace(re, func)
                                 ^

TypeError: data.replace is not a function
	at Object.encodeXML (C:\Users\[PROJECT FOLDER]\node_modules\entities\lib\encode.js:58:6)
	at formatAttrs (C:\Users\[PROJECT FOLDER]\node_modules\dom-serializer\index.js:67:62)
	at renderTag (C:\Users\[PROJECT FOLDER]\node_modules\dom-serializer\index.js:132:17)
	at module.exports (C:\Users\[PROJECT FOLDER]\node_modules\dom-serializer\index.js:113:17)
	at render (C:\Users\[PROJECT FOLDER]\node_modules\cheerio\lib\static.js:70:10)
	at Object.exports.html (C:\Users\[PROJECT FOLDER]\node_modules\cheerio\lib\static.js:94:10)
	at initialize.exports.html (C:\Users\[PROJECT FOLDER]\node_modules\cheerio\lib\api\manipulation.js:368:14)
	at Object.<anonymous> (C:\Users\[PROJECT FOLDER]\tests\test.js:52:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

Any idea? 
_**My goal is to extract the html content in a node as a string.**_

**Comment by jugglinmike** [comment] 2017-02-11 22:14
I'm unable to reproduce this behavior in the latest release of Cheerio
(0.22.0)--see below. Can you verify that you are running the latest release,
and if so, could you share the output of `npm ls`?

    $ cat index.js
    var cheerio = require('cheerio');
    var $ = cheerio.load(`<body><div id="example"> <a href=""> Some content</a> </div></body>`);
    console.log($('body').find('#example').html());
    [mike@bruce gh-970]$ node index.js 
     <a href=""> Some content</a> 
    [mike@bruce gh-970]$ npm ls
    /home/mike/projects/oss/cheerio/playground/gh-970
    └─┬ cheerio@0.22.0
      ├─┬ css-select@1.2.0
      │ ├── boolbase@1.0.0
      │ ├── css-what@2.1.0
      │ ├─┬ domutils@1.5.1
      │ │ └── domelementtype@1.3.0
      │ └── nth-check@1.0.1
      ├─┬ dom-serializer@0.1.0
      │ └── domelementtype@1.1.3
      ├── entities@1.1.1
      ├─┬ htmlparser2@3.9.2
      │ ├── domelementtype@1.3.0
      │ ├── domhandler@2.3.0
      │ ├── domutils@1.5.1
      │ ├── inherits@2.0.3
      │ └─┬ readable-stream@2.2.2
      │   ├── buffer-shims@1.0.0
      │   ├── core-util-is@1.0.2
      │   ├── isarray@1.0.0
      │   ├── process-nextick-args@1.0.7
      │   ├── string_decoder@0.10.31
      │   └── util-deprecate@1.0.2
      ├── lodash.assignin@4.2.0
      ├── lodash.bind@4.2.1
      ├── lodash.defaults@4.2.0
      ├── lodash.filter@4.6.0
      ├── lodash.flatten@4.4.0
      ├── lodash.foreach@4.5.0
      ├── lodash.map@4.6.0
      ├── lodash.merge@4.6.0
      ├── lodash.pick@4.4.0
      ├── lodash.reduce@4.6.0
      ├── lodash.reject@4.6.0
      └── lodash.some@4.6.0

**Comment by jugglinmike** [comment] 2017-03-05 18:49
We won't be able to help without some more information. It's been a few weeks, so I'm going to close this issue. If anyone has a similar problem, let us know and we can re-open.

**Closed by jugglinmike** 2017-03-05 18:49 UTC
Labels: Needs info
