### ISSUE TITLE
The number of child elements of the element is not what I expected

### ISSUE THREAD

**Issue by Vinsurs** [cheeriojs/cheerio#1943] opened 2021-06-20 11:40 UTC
### Here is an HTML Fragment:
```html
<div id="blog-news">
    <br /><a href="https://github.com/Plen-wang/">https://github.com/Plen-wang/<a />
        <br />
        <hr />
        <div class="profile_block">
            nick：
            <a href="https://home.cnblogs.com/u/wangiqngpei557/">
                www
            </a>
            <br />
            years：
            <a href="https://home.cnblogs.com/u/wangiqngpei557/" title="hostTime：2010-11-17">
                10
            </a>
            <br />
            honors： <a href="https://www.cnblogs.com/expert/">recommend</a>
            <br />
            fans：
            <a href="https://home.cnblogs.com/u/wangiqngpei557/followers/">
                2924
            </a>
            <br />
            hot：
            <a href="https://home.cnblogs.com/u/wangiqngpei557/followees/">
                120
            </a>
            <div id="p_b_follow"></div>
            <script>getFollowStatus('f3377231-14f2-df11-ac81-842b2b196315');</script>
        </div>
</div>
```
I save the above HTML code fragment as variable html, just like this,
```js
const cheerio = require("cheerio")
const $ = cheerio.load(html)

const items = $(".profile_block").last().children("a")
console.log(items.length)  // the expected result is 5, but the print out 6
```
Is it a bug? confuse me a lot...

**Comment by fb55** [comment] 2021-08-14 15:35
Assuming this is a duplicate of #1988

**Closed by fb55** 2021-08-14 15:35 UTC
