### ISSUE TITLE
Using $ directly does not work in rc9 (was working in rc6)

### ISSUE THREAD

**Issue by cgarethc** [cheeriojs/cheerio#1848] opened 2021-05-08 03:15 UTC
I use the form of calling Cheerio documented in the README as "Optionally, you can also load in the HTML by passing the string as the context"

In RC6 this code succeeds and prints the details of the element:
`
const $ = require('cheerio');
const html = '<html><body><div id="a1"/></body></html>';
console.log($('#a1', html));
`

In RC9, the same code produces this output:
`TypeError: $ is not a function`

**Comment by fb55** [comment] 2021-05-08 22:39
Duplicate of #1846. Thanks for mentioning the README, I've removed the `require` there to discourage usage of this pattern.

**Closed by fb55** 2021-05-08 22:39 UTC
