### ISSUE TITLE
Can´t select elements based on their position in the document

### ISSUE THREAD

**Issue by WilliamBelini** [cheeriojs/cheerio#3547] opened 2023-12-15 19:10 UTC
From https://cheerio.js.org/docs/basics/selecting 

Have a command documentation that inform you can select elements based on their position, like

```ts
const $p = $('p:first');
```

but if I want select `$p = $('div div.first button').attr('onclick')` it returns null. 

if I write just
```ts
 $('div div button').attr('onclick'),
```
 
 it returns the first value

Always I need do
```ts
 $('div div button').each((index,value) =>
 $(value).attr('onclick')
```
 
 (yes, the comand 'each' return the div>div elements). 
 
 And discard the 2 first elements to get my value.
 
 I think it be more simple like
```ts
  $('div div[2] button').attr('onclick')
```
  
  Selecting the div position with "[2]", like an array element position.

Exist some form that I can't need make the 'each' command to return the values from 3th div?

If I write like the div:second, Google App Script retuns "Error: unmatched pseudo-class :second"

Thanks
![gift](https://github.com/cheeriojs/cheerio/assets/20886231/0d4d1625-6aee-4f3e-b194-33718f29d497)

**Comment by fb55** [comment] 2023-12-16 11:06
What version of Cheerio are you using? Note that positional selectors are only available in the latest RC release.

**Comment by WilliamBelini** [comment] 2023-12-16 15:35
I'm using the last version avaible from Google App Script

Em sáb., 16 de dez. de 2023 08:07, Felix Boehm ***@***.***>
escreveu:

**Comment by fb55** [comment] 2024-08-08 08:10
I cannot find a version of Cheerio in Google App Script, so closing this as cannot reproduce. Please let me know if you have further details!

**Closed by fb55** 2024-08-08 08:10 UTC

**Comment by WilliamBelini** [comment] 2024-08-09 00:59
![image](https://github.com/user-attachments/assets/05000048-16f4-49ff-b0fd-c976d64ed1e9)
It is very simple. I thing couldn't explained easily. 

Imagine you have a link in a button, and you want to select it. 
The code show like that

```
<div>
   <div>
   <div>
   <div>
         <button onclick: "I dont want this link">
         <button onclick: "My beautiful link">
```


The unique form I can use to do it (select my beautiful link) is running a loop, using the function "each".
I wanna write something like this `$(div div[3] button[2])` to don't need run a loop always.

**Comment by fb55** [comment] 2024-08-09 07:26
Thanks for the link! cheeriogs is using a version of cheerio that does not support positional selectors. Once it upgrades to the latest version, you'll be able to use `:eq(2)` to select the second element. 

cc @tani

**Comment by tani** [comment] 2024-08-09 09:10
Noted with thanks. I'll update it. After the deployment, I am going to post the message here as soon as possible.

**Comment by WilliamBelini** [comment] 2024-08-09 23:47
Hi,thank youEm 9 de ago. de 2024 10:32, TANIGUCHI Masaya ***@***.***> escreveu:
Hi, v15 is available now. You can use 1.0.0-rc12 on Google Apps Script. Cheers.
