### ISSUE TITLE
incorrect parsing for non-closed <th>

### ISSUE THREAD

**Issue by joncasey** [cheeriojs/cheerio#696] opened 2015-04-07 01:04 UTC
```node
var $ = cheerio.load('<html><body><table><tr><th>TH<td>TD1<td>TD2</tr></table>')
console.log( $('th').html() )
```
shows
```
TH<td>TD1</td><td>TD2</td>
```
should be
```
TH
```

**Comment by pyhedgehog** [comment] 2015-04-08 14:16
Duplicate of #694.

**Closed** 2015-04-08 14:17 UTC
