### ISSUE TITLE
`append()` and `prepend()` messing up with DOM on @1.0.0-rc.5

### ISSUE THREAD

**Issue by cburatto** [cheeriojs/cheerio#1785] opened 2021-03-26 04:02 UTC
Disclaimer: not very experienced with Cheeriojs

Windows 10
Node.js 14.15.4

Using a very simple source HTML file (**note** file is `UTF-8 BOM` with Windows `CRLF` EOLs):

```
<!DOCTYPE html>
<html>
<head>
<title></title>
<meta charset ='utf-8'/></head>
<body>
<strong><span style="font-size: 14pt;">January 1 – December 31, 2021<br /></span></strong>
</body>
</html>
```

I have a very simple code to prepend a `<style>` element with inline css to the `<head>` element. 

```
let $ = cheerio.load(data);
let htmlString= fs.readFileSync(htmlFile, 'utf8');
let $ = cheerio.load(htmlString);
$('head').prepend('<style type="text/css">cssData</style>');
fs.writeFileSync(fileName, $.root().html(), 'utf8');
```
When using `@1.0.0-rc.5`, the elements are messed up. Look how `title` and `meta` are moved to the `body`. Also, `<!DOCTYPE html>` is removed. (BOM is removed, EOLs change from `CRLF` to `LF`)

```
<html>
<head>
<style type="text/css">﻿
{{myCSS}}
</style>
</head>
<body>﻿
<title></title>
<meta charset="utf-8">
<strong><span style="font-size: 14pt;">January 1 – December 31, 2021<br></span></strong>
</body>
</html>
```

This does not happen with `@0.22.0`. However, the BOM is converted to entities (line breaks change from CRLF to LF):

`&#xFEFF;<!DOCTYPE html>`

(maybe there are options to load/serialize the string and keep BOM, but I can't find documentation or articles)

**Comment by cburatto** [comment] 2021-03-26 04:22
Update: BOM issue is solved by loading with `decodeEntities: false`:

`let $ = cheerio.load(data, { decodeEntities: false });`

`@1.0.0-rc.5` DOM mixup persists.

**Comment by fb55** [comment] 2021-03-26 05:17
Very interesting, looks like a parse5 issue 👀

**Comment by fb55** [comment] 2021-03-26 05:18
Could you check if this mixup persists if you don't modify the DOM?

**Comment by cburatto** [comment] 2021-03-26 06:18
Just confirmed: Issue does not occur if I don't modify (just load and serialize)

**Comment by 5saviahv** [comment] 2021-03-26 19:25
- This [CRLF conversion](https://github.com/inikulin/parse5/blob/9c683e154b8bbdc94237580680a934348406d1a2/packages/parse5/lib/tokenizer/preprocessor.js#L108-L120) is done by parse5
- with intact BOM parse5 seems to get confused, it is not whitespace so it switches to `in_body` and ignores `doctype` since directive can not happen in html `body`.

**Comment by cburatto** [comment] 2021-04-07 15:47
Apologies for the delay -- I confirm that if you remove the BOM before loading on Cheerio the append/preppend work without messing the DOM.

Not sure if this issue should be closed or if there should be a plan to deal with BOM by design.

**Comment by fb55** [comment] 2021-06-08 11:38
Looks like a parse5 bug. Closing this issue as we can't do anything about this from here.

cc @frank-dspeed, this should be interesting for your rewrite.

**Closed by fb55** 2021-06-08 11:38 UTC
Labels: Parser-specific

**Comment by niemyjski** [comment] 2021-06-17 03:45
@fb55 does this also explain this issue I'm seeing with my markup getting all collapsed?

```js
console.log(src)
var $ = cheerio.load(src, { lowerCaseAttributeNames: false });
console.log($.html())
```

## src

```html
<!DOCTYPE html>
<html version="1">
<head>
                <title></title>
                <link href="css1.css" rel="stylesheet">
                <link href="css2.css" rel="stylesheet">
                <link href="css3.css" rel="stylesheet">
                <script src="js1.js"></script>
                <script src="js2.js"></script>
        </head>
        <body>
                <div id="csslist"></div>
                <div id="jslist"></div>
        </body>
</html>
```

## output
```html
<!DOCTYPE html><html version="1"><head>
                <title></title>
                <link href="css1.css" rel="stylesheet">
                <link href="css2.css" rel="stylesheet">
                <link href="css3.css" rel="stylesheet">
                <script src="js1.js"></script>
                <script src="js2.js"></script>
        </head>
        <body>
                <div id="csslist"></div>
                <div id="jslist"></div>


</body></html>
```

**Comment by fb55** [comment] 2021-06-17 11:04
@niemyjski No, this is caused by parse5 producing a spec-compliant DOM structure. You might want to run prettier on the output, or set the `_useHtmlparser2` option

**Comment by frank-dspeed** [comment] 2021-06-17 22:20
i know why this happens its the tokenizer implementation it can only get fixed by a rewrite. @fb55 

the parse5 implementation is a set of many switch statements. and as you know the tests are sub optimal to target this but i will track this issue as one of my main reasons for improving parse5 was also to improve cheerio.

**Comment by frank-dspeed** [comment] 2021-07-01 07:31
# Note for my self this issue is related to the preprocessor implementation
```js
//NOTE: all U+000D CARRIAGE RETURN (CR) characters must be converted to U+000A LINE FEED (LF) characters
    if (cp === CODE_POINTS.CARRIAGE_RETURN) {
      preprocessor.skipNextNewLine = true;
      return CODE_POINTS.LINE_FEED;
    }
```

**Comment by frank-dspeed** [comment] 2021-07-01 07:44
@fb55 maybe you want to reopen that issue as i will implement that as option into the parser to choose between CRLF and LF

in a later step i will add autodetection of CRLF and LF and try to preserve the charakters.

**Comment by frank-dspeed** [comment] 2021-07-01 08:43
I was trying to handle that then i found out it is not handle able in parse6 let me explain

parse5 produces a AST not a file the AST is not aware of the file it got created from and should not be aware of that
so the BOM gets lost by design this is the intendeed behavior. Same for LF and CRLF 

## Solution
i will implement inside parse6 a serializer that supports bom and CRLF as also a parser method that detects BOM and CRLF then preserves that State and finally does https://github.com/cheeriojs/cheerio/issues/1785#issuecomment-808460805

I think that is the total correct way to go cheerio can then use that method in its file reading Method to support BOM and CRLF if the input file is formarted like that. so it is in fact a cheerio issue as cheerio handels files already nad parse5 does not handle files at present but will handle them in future.
