### ISSUE TITLE
.replaceWith() not affecting all elements

### ISSUE THREAD

**Issue by petemill** [cheeriojs/cheerio#687] opened 2015-03-19 07:04 UTC
Using v.0.18 and v.0.13, on a cheerio object with multiple elements, calling .replaceWith() does not affect all elements.

For example the following test script:

``` javascript
var cheerio = require('cheerio');
console.log(cheerio.version);
var html = '<h1><div>one</div></h1><h2>two</h2><div><h1><div>three</div></h1><h2>four</h2><h1>five</h1><h1>six</h1></div>';
console.log(html)
var $ = cheerio.load(html);

console.log($('h1').length);
$('h1').each(function(i, elem){
    $(elem).replaceWith($('<h3>Replaced</h3>'));
});
console.log($('h3').length);
console.log($.html());


var $ = cheerio.load(html);

console.log($('h1').length);
$('h1').replaceWith($('<h3>Replaced</h3>'));
console.log($('h3').length);
console.log($.html());
```

Output:

```
0.18.0
<h1><div>one</div></h1><h2>two</h2><div><h1><div>three</div></h1><h2>four</h2><h1>five</h1><h1>six</h1></div>
4
4
<h3>Replaced</h3><h2>two</h2><div><h3>Replaced</h3><h2>four</h2><h3>Replaced</h3><h3>Replaced</h3></div>
4
1
<h2>two</h2><div><h2>four</h2><h3>Replaced</h3></div>
```

As can be seen, iterating through each element and calling .replaceWith on each element works as expected, but calling .replaceWith on a cheerio object with all 4 matched elements, only 1 gets replaced. Weirdly enough, in cheerio v0.13, two get replaced. The documentation states that all should be replaced.

**Comment by fb55** [comment] 2020-12-12 06:29
Unable to reproduce, closing.

**Closed by fb55** 2020-12-12 06:29 UTC
