### ISSUE TITLE
Module parse failed " export * as DomUtils from "domutils",  "export * as foreignContent from './common/foreign-content.js'"

### ISSUE THREAD

**Issue by Fabioni** [cheeriojs/cheerio#2669] opened 2022-07-30 11:56 UTC
using  `1.0.0-rc.11 `or `1.0.0-rc.12` I get the following error:

```
 ERROR  Failed to compile with 2 errors


 ERROR  in ./node_modules/htmlparser2/lib/esm/index.js

Module parse failed: Unexpected token (59:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     return getFeed(parseDOM(feed, options));
| }
> export * as DomUtils from "domutils";
| // Old name for DomHandler
| export { DomHandler as DefaultHandler };

 @ ./node_modules/cheerio/lib/esm/index.js 11:0-68 13:6-26
 @ ./node_modules/babel-loader/lib??ref--3-0!./node_modules/vue-loader/lib??vue-loader-options!./components/ShowPost.vue?vue&type=script&lang=js&
 @ ./components/ShowPost.vue?vue&type=script&lang=js&
 @ ./components/ShowPost.vue
 @ ./.nuxt/components/index.js
 @ ./.nuxt/components/plugin.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js


 ERROR  in ./node_modules/parse5/dist/index.js

Module parse failed: Unexpected token (6:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { serialize, serializeOuter } from './serializer/index.js';
| /** @internal */
> export * as foreignContent from './common/foreign-content.js';
| /** @internal */
| export * as html from './common/html.js';

 @ ./node_modules/cheerio/lib/esm/parsers/parse5-adapter.js 2:0-79 22:10-23 23:10-23 48:18-32
 @ ./node_modules/cheerio/lib/esm/index.js
 @ ./node_modules/babel-loader/lib??ref--3-0!./node_modules/vue-loader/lib??vue-loader-options!./components/ShowPost.vue?vue&type=script&lang=js&
 @ ./components/ShowPost.vue?vue&type=script&lang=js&
 @ ./components/ShowPost.vue
 @ ./.nuxt/components/index.js
 @ ./.nuxt/components/plugin.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

using `^1.0.0-rc.10` it works.

I am using nuxt2, which uses webpack 4

**Comment by fb55** [comment] 2022-08-03 10:38
Duplicate of https://github.com/cheeriojs/cheerio/issues/2545

**Closed by fb55** 2022-08-03 10:38 UTC

**Comment by Fabioni** [comment] 2022-08-03 10:50
Hey, the linked issue is already closed, but the problem still exist, so I don't see why you close this issues.

**Comment by fb55** [comment] 2022-08-03 11:28
To quote my reply to the linked issue:

> I understand that it is annoying to have to work around this issue. Unfortunately, I don't see an easy way to work around this issue without negative side effects for users with modern tooling, meaning that this won't be fixed. Hope that makes sense!
