### ISSUE TITLE
Typescript Compilation Errors

### ISSUE THREAD

**Issue by paularah** [cheeriojs/cheerio#1894] opened 2021-05-30 13:05 UTC
The new typescript definition breaks my build with the error below

`
node_modules/cheerio/lib/types.d.ts:2:78` - error TS1110: Type expected.
2 declare type AlphaNumeric = LowercaseLetters | Uppercase<LowercaseLetters> | `${number}`;
node_modules/cheerio/lib/types.d.ts:8:36 - error TS1110: Type expected.
8 export declare type SelectorType = `${SelectorSpecial}${AlphaNumeric}${string}` | `${AlphaNumeric}${string}`;                                     
Found 2 errors
`

Node version: 12.22.1

**Comment by fb55** [comment] 2021-05-30 14:57
Duplicate of #1855. Tl;dr you'll have to bump your TS version.

**Closed by fb55** 2021-05-30 14:57 UTC

**Comment by paularah** [comment] 2021-05-30 16:59
Thanks!
