### ISSUE TITLE
javscript in between Text

### ISSUE THREAD

**Issue by crosofg** [cheeriojs/cheerio#924] opened 2016-09-27 17:02 UTC
I am trying to extract text. I am getting javascript code inside the text output.

```js
that the attackers were its citizens.!function(a,n,e,t,r){tagsync=e;var c=window[a];if(tagsync){var d=document.createElement("script");d.src="http://3608.tm.zedo.com/v1/61c8aaf4-e5cb-4628-aeda-83ec5db6499b/atm.js",d.async=!0;var i=document.getElementById(n);if(null==i||"undefined"==i)return;i.parentNode.appendChild(d,i),d.onload=d.onreadystatechange=function(){var a=new zTagManager(n);a.initTagManager(n,c,this.aync,t,r)}}else document.write("<script src='http://3608.tm.zedo.com/v1/61c8aaf4-e5cb-4628-aeda-83ec5db6499b/tm.js?data="+a+"'><"+"/script>")}("datalayer","z92426d7a-414b-4e66-8acc-c99963e60906",true, 1 , 1);The weeks before the strike on the army ca
```

What could be the issue?

**Comment by Abromide** [comment] 2017-03-06 10:41
Can you post your code?

**Comment by fb55** [comment] 2017-03-10 04:48
Duplicate of #986

**Comment by fb55** [comment] 2017-03-10 04:49
`$('script, style').remove()` should help, but this is a bug.

**Closed by fb55** 2017-03-10 04:48 UTC
