### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by wheresrhys** [cheeriojs/cheerio#856] opened 2016-04-28 14:23 UTC
We've been experiencing memory leaks since updating from cheerio 0.19 to 0.20. Rolling back a version solved the problem. I've been unable to identify the exact cause, but here are some application and environment details:
- node: node-v4.3.1-linux-x64
- os: Linux 3.13.0-79-generic x86_64 ( a standard heroku VM)
- code https://github.com/Financial-Times/next-article/tree/c38a1146b032c69a727d344295480dddc2f34f7a/server/transforms (test fixtures will give you an indication of what content is parsed https://github.com/Financial-Times/next-article/tree/c38a1146b032c69a727d344295480dddc2f34f7a/test/fixtures. You may even be able to run the tests locally without needing access to any of our secured services)

Let me know if you need any more details

![image](https://cloud.githubusercontent.com/assets/447559/14889126/64bfca76-0d55-11e6-959e-4ddc20980fae.png)

**Comment by akashkamboj** [comment] 2016-05-02 17:35
+1 
was struggling a lot with the memory issue and rolling back to 0.19 gave me a big relief.

**Comment by stocarul** [comment] 2016-05-11 15:25
Confirm the problem. Downgraded to `0.19` and seems to be working so far.

**Comment by luanmuniz** [comment] 2016-05-14 16:16
@wheresrhys Is there any way we can modify the code so this problem happen faster? That way we can get all the commits from version 0.19 and 0.20 and test it one by one and find where the problem is

**Comment by vaseker** [comment] 2016-05-16 08:14
Some stacktrace

> ==== JS stack trace =========================================
Security context: 0x2ddda71b4629 <JS Object>
    1: substring(aka substring) [native string.js:~483] [pc=0x1662d7b14163] (this=0xf35810aad09 <Very long string[38641]>,S=18961,T=18964)
    2: _parse [/home/ubuntu/www/survarium-api/server/v2/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:~635] [pc=0x1662d706a0f0] (this=0xf35
810b3fc1 <a Tokenizer with map 0x2716ac9d0ea9>)
    3: parseDOM [/home/ubuntu/www/survarium-api/server...
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory

**Comment by wheresrhys** [comment] 2016-05-16 20:23
The memory leak was only really apparent in production under heavy load and I can't really justify attempting to recreate the bug again I'm afraid

**Comment by warlock** [comment] 2016-05-27 08:17
Have a same problem. I'm downgraded to 0.19.

**Comment by tambovchanin** [comment] 2016-07-29 13:54
Have the same problem

**Comment by bjaka-max** [comment] 2016-10-18 03:14
I have a same problem. In heap snapshot, i see, that all my variables with text from cheerio, is "sliced string" which contain all html page. I`m use dirty (but working) solution
	function unleak(s) {
		return (' ' + s).substr(1);
	}
for all my values from cheerio. It eliminate memory leaks.

**Comment by Lagg** [comment] 2016-10-23 19:08
This issue remains true for me as well. Really wrecks production. I advise remaining on 0.19 for anyone on the fence still.

**Comment by Anthony-Mckale** [comment] 2019-02-08 13:24
had same issue, this from above worked a treat for me

function unleak(s) {
return (' ' + s).substr(1);
}

**Comment by fb55** [comment] 2020-10-15 06:06
Fixed on the 1.0.0-RC versions.

**Closed by fb55** 2020-10-15 06:06 UTC
