### ISSUE TITLE
Property 'data' does not exist on type 'Node'.ts(2339) - since rc.6

### ISSUE THREAD

**Issue by DavideViolante** [cheeriojs/cheerio#1925] opened 2021-06-08 15:58 UTC
I'm using cheerio in a TypeScript project.
**Since rc6** version I get this error:

```
Property 'data' does not exist on type 'Node'.ts(2339)
```

The code is:
```ts
  import { load as cheerioLoad } from 'cheerio';
  ...
  const $ = cheerioLoad(response.data); // this is a text/html get response from axios
  const textDom = $('#some_element');
  let someVar;
  if (myVar === 'example') {
    someVar = textDom.find('p').get(2).children[0].data; // ERROR
  } else {
    someVar = textDom.find('#asd > div:nth-child(3)').get(0).children[0].data; // ERROR
  }
``` 

If I print `textDom.find('p').get(2).children[0]` data is a property:
```ts
<ref *1> Node {
  type: 'text',
  data: 'The text I want to get is here', // <------- YES PROPERTY data EXISTS
  parent: <ref *2> Node {
    type: 'tag',
    name: 'p',
    namespace: 'http://www.w3.org/1999/xhtml',
    attribs: [Object: null prototype] { class: 'centerBold' },
    'x-attribsNamespace': [Object: null prototype] { class: undefined },
    'x-attribsPrefix': [Object: null prototype] { class: undefined },
    children: [ [Circular *1] ],
    parent: Node {
      type: 'tag',
      name: 'div',
      namespace: 'http://www.w3.org/1999/xhtml',
      attribs: [Object: null prototype],
      'x-attribsNamespace': [Object: null prototype],
      'x-attribsPrefix': [Object: null prototype],
      children: [Array],
      parent: [Node],
      prev: [Node],
      next: [Node]
    },
    prev: Node {
      type: 'text',
      data: '\n\t\t\t',
      parent: [Node],
      prev: [Node],
      next: [Circular *2]
    },
    next: Node {
      type: 'text',
      data: '\n\t\t\t',
      parent: [Node],
      prev: [Circular *2],
      next: [Node]
    }
  },
  prev: null,
  next: null
}
```

Intellisense VS Code:
![nodatacheerio](https://user-images.githubusercontent.com/6844116/121219738-4f80a000-c884-11eb-8232-665cedac6e9c.gif)

Any help is appreciated, thanks.

**Comment by DavideViolante** [comment] 2021-06-09 09:06
A workaround is:
```ts
(textDom.find('p').get(2).children[0] as any).data; 
```
but I don't think is the correct cleanest way to fix it.
What kind of `type` is children[0]? Why `Node` does not have `data` property?

**Comment by fb55** [comment] 2021-06-09 09:26
This issue is that only text nodes have a `data` property. So for your workaround, you could import `Text` from Cheerio, then do:

```js
(textDom.find('p').get(2).children[0] as Text).data; 
```

Or, if you want to make sure you are actually dealing with a text node:

```js
import { isText } from 'domhandler';

// ...

const child = textDom.find('p').get(2).children[0]
if (isText(child)) {
  child.data
}
```

I am contemplating having cheerio re-export the `is*` functions for all node types from domhandler to make this easier, but haven't made up my mind on what the best interface would be.

**Comment by fb55** [comment] 2021-06-09 09:26
Closing as a duplicate of #1854.

**Closed by fb55** 2021-06-09 09:26 UTC

**Comment by kluplau** [comment] 2023-06-30 10:05
You could also make a guard function
```ts
function isText(node: Node): node is Text {
    return node.nodeType === Node.TEXT_NODE;
}

if (isText(child)) {
    console.log(child.data);
}
