### ISSUE TITLE
Package subpath  './lib/api/traversing' is not defined by "exports" in /home/ container/node_modules/cheerio/package.json

### ISSUE THREAD

**Issue by Hendra827** [cheeriojs/cheerio#2551] opened 2022-05-24 16:20 UTC
![IMG_20220524_210725](https://user-images.githubusercontent.com/31788233/170084269-5eeb51a1-9fdb-4aac-9c43-e42288036160.jpg)

How to fix?
The same issue can't fix

**Comment by eahenke** [comment] 2022-05-24 21:43
Presumably the same error as https://github.com/cheeriojs/cheerio/issues/2547.  Cheerio seems to no longer allow deep imports, but  a number of packages (including Enzyme) seem to be relying on deep imports and now break.

**Comment by soutarm** [comment] 2022-05-31 01:10
We're seeing the same thing (via Enzyme)

**Comment by fb55** [comment] 2022-06-01 23:55
Duplicate of https://github.com/cheeriojs/cheerio/issues/2547

**Closed by fb55** 2022-06-01 23:55 UTC
