### ISSUE TITLE
New Release Broken?

### ISSUE THREAD

**Issue by mgtballison** [cheeriojs/cheerio#3986] opened 2024-08-09 22:18 UTC
We're getting this error as of about 3 hours ago. Wondering if it is related to the latest release of cheerio.

```
> astro check && astro build
9:11:58 PM [vite] Error when evaluating SSR module /opt/atlassian/pipelines/agent/build/website/astro.config.mjs: failed to import "astro-icon"
|- file:///opt/atlassian/pipelines/agent/build/website/node_modules/@iconify/tools/lib/svg/index.mjs:1
import cheerio from 'cheerio';
       ^^^^^^^
SyntaxError: The requested module 'cheerio' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async nodeImport (file:///opt/atlassian/pipelines/agent/build/website/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52928:15)
    at async ssrImport (file:///opt/atlassian/pipelines/agent/build/website/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52786:16)
    at async eval (/opt/atlassian/pipelines/agent/build/website/astro.config.mjs:7:31)
    at async instantiateModule (file:///opt/atlassian/pipelines/agent/build/website/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52844:5)
[astro] Unable to load your Astro config
```

**Comment by NeKosmico** [comment] 2024-08-09 23:57
> We're getting this error as of about 3 hours ago. Wondering if it is related to the latest release of cheerio.
> 
> ```
> > astro check && astro build
> 9:11:58 PM [vite] Error when evaluating SSR module /opt/atlassian/pipelines/agent/build/website/astro.config.mjs: failed to import "astro-icon"
> |- file:///opt/atlassian/pipelines/agent/build/website/node_modules/@iconify/tools/lib/svg/index.mjs:1
> import cheerio from 'cheerio';
>        ^^^^^^^
> SyntaxError: The requested module 'cheerio' does not provide an export named 'default'
>     at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
>     at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
>     at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
>     at async nodeImport (file:///opt/atlassian/pipelines/agent/build/website/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52928:15)
>     at async ssrImport (file:///opt/atlassian/pipelines/agent/build/website/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52786:16)
>     at async eval (/opt/atlassian/pipelines/agent/build/website/astro.config.mjs:7:31)
>     at async instantiateModule (file:///opt/atlassian/pipelines/agent/build/website/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52844:5)
> [astro] Unable to load your Astro config
> ```

I still have that same error :'/

**Comment by rafipiccolo** [comment] 2024-08-10 00:19
it seems there's no default export anymore.

But the import style of the documentation works.

```
// before
import cheerio from 'cheerio';
// after
import * as cheerio from 'cheerio';
```

needs to be fixed on every dependent package
or maybe cheerio would agree to re-add a default export

**Comment by NeKosmico** [comment] 2024-08-10 00:32
> it seems there's no default export anymore.
> 
> But the import style of the documentation works.
> 
> ```
> // before
> import cheerio from 'cheerio';
> // after
> import * as cheerio from 'cheerio';
> ```
> 
> if that remains, it will require a fix on every dependent package. or maybe cheerio would agree to re-add a default export

Yes it works, but there are projects that use the old version, for now for me a solution was to use the old version exact 

```
{
"dependencies": {
  "cheerio": "1.0.0-rc.12"
}
}
```

**Comment by fb55** [comment] 2024-08-10 09:53
The default import had been deprecated for several years now, and was removed with the new release: https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0

There were a number of bugs caused by having the default export, which are finally a thing of the past. I appreciate that it is annoying having to update your imports, but you are getting a less error-prone experience in exchange.

**Closed** 2024-08-10 09:53 UTC

**Comment by mgtballison** [comment] 2024-08-12 15:08
@fb55 Thanks for your reply! Appreciate the help!
