### ISSUE TITLE
text() not working as expected in 1.0.0-rc2

### ISSUE THREAD

**Issue by plumpNation** [cheeriojs/cheerio#1112] opened 2017-11-22 00:20 UTC
1.0.0-rc2

```
const svgString = '<?xml version="1.0" encoding="utf-8"?><svg><style>path{fill:red}</style></svg>';

const $ = cheerio.load(svgString, {xmlMode: true);

$('styles').each((index, element) => {
    console.log($(element).text()); // outputs: ''
    console.log($(element).html()); // outputs: 'path{fill:red}'
});
```

I have rolled back to 0.22.0 and it works fine.

**Comment by nover** [comment] 2017-11-24 14:55
Having a similar issue here with the following test case in our project:

mocha v4 test suite with unexpected required as `expect`
```
it('returns text of title tag', () => {
    const html = '<html><head><title><b>bold</b> title</title>' +
      '</head><body><h1>Hello</h1></body></html>';

    const $ = cheerio.load(html);
    const theTitle = $('title').text();
    expect('bold title', 'to be', theTitle);
  });
```

failing with the assertion error:
```
UnexpectedError:
expected '<b>bold</b> title' to be 'bold title'
```

So the `<b>` tags are not properly stripped.

**Comment by fb55** [comment] 2018-03-11 16:20
Duplicate of #1050

@nover's case is expected — `<title>` tags are special that way.

**Closed by fb55** 2018-03-11 16:20 UTC
