### ISSUE TITLE
find() convert `xlink:href` to `href`

### ISSUE THREAD

**Issue by exitudio** [cheeriojs/cheerio#1101] opened 2017-11-02 04:24 UTC
`cheerio@^1.0.0-rc.2` automatically converts `xlink:href` to `href` when using `find()`.

```js
cheerio.load('')('<span><svg ><use xlink:href="#1" /></svg></span>').find('use').prop('xlink:href') //undefined
cheerio.load('')('<span><svg ><use xlink:href="#1" /></svg></span>').find('use').prop('href') //#1
```

Since, Safari doesn't support `href` without the "xlink" prefix in svg yet. Maybe, leave `xlink:href` as it was in `cheerio@^0.22.0` is better?

**Comment by peter-mouland** [comment] 2017-11-02 13:57
some background to this issue: https://github.com/airbnb/enzyme/issues/1297#issuecomment-341313889

**Comment by fb55** [comment] 2017-12-25 17:47
We're using [parse5](https://github.com/inikulin/parse5/) for parsing, this seems to be an issue with its svg implementation. cc'ing @inikulin

**Comment by inikulin** [comment] 2017-12-25 22:32
parse5 parses `xlink:href` in SVG namespace as a namespaced attribute ([as per spec](https://html.spec.whatwg.org/multipage/parsing.html#adjust-foreign-attributes)). So,  such an attribute is parsed as an attribute with the name `href` and `xlink` prefix. Cheerio uses `htmlparser2` tree adapter and since original htmlparser2 hasn't concept of namespaced attributes, attribute prefixes are stored in parse5-specific `x-attribsPrefix` map on element:
![image](https://user-images.githubusercontent.com/453071/34343346-0d949046-e9c3-11e7-8fb9-e33b1a756abb.png)
*(Interactive playground: https://runkit.com/inikulin/5a417be9053db70012a5954e)*

It seems like Cheerio needs some additional work to support namespaced attributes in parse5 AST.

**Comment by fb55** [comment] 2017-12-25 22:35
Kk, so this is a dom-serializer shot-coming. What was the reasoning why we didn't use parse5 as a serialiser?

**Comment by kokers** [comment] 2019-02-25 10:59
Is this something that will have a fix in some near future?

**Comment by fb55** [comment] 2020-12-22 20:13
This should be fixed with the latest release.

**Closed by fb55** 2020-12-22 20:13 UTC

**Comment by ljharb** [comment] 2020-12-22 21:27
@fb55 thanks, confirmed fixed in rc 5 in enzyme's tests!

**Comment by ljharb** [comment] 2020-12-22 21:53
@fb55 hmm, the tests passed locally but are failing in CI in node 4: https://travis-ci.com/github/enzymejs/enzyme/builds/210326410

Specifically, `parse5-htmlparser2-tree-adapter` is using object destructuring syntax, which means including it is a breaking change :-/

**Comment by ljharb** [comment] 2020-12-22 21:58
Filed #1585 for this.
