### ISSUE TITLE
decodeEntities false  code tag

### ISSUE THREAD

**Issue by huanz** [cheeriojs/cheerio#1198] opened 2018-05-14 11:18 UTC
```javascript
const $ = cheerio.load(`<code>&lt;script src&gt;</code>`, {
  decodeEntities: false
});
console.log($.html());
```

output

```html
<html><head></head><body><code><script src></code></body></html>
```

you can see that the string `&lt;script src&gt;` has been unescaped

**Comment by Jasonlhy** [comment] 2018-05-29 06:14
It seems that you need to set it to true.
```
$ = cheerio.load(`<code>&lt;script src&gt;=></code>`, {   decodeEntities: true }); console.log($.html());
<html><head></head><body><code>&lt;script src&gt;=&gt;</code></body></html>
```

**Comment by huanz** [comment] 2018-05-29 08:37
@Jasonlhy if i set true, the Chinese will be decoded, eg:

```
const $ = cheerio.load(`<p>哈哈哈哈</p><code>&lt;script src&gt;</code>`, {
  decodeEntities: true
});
console.log($.html());
```

output:

```
<html><head></head><body><p>&#x54C8;&#x54C8;&#x54C8;&#x54C8;</p><code>&lt;script src&gt;</code></body></html>
```

**Comment by senwzz** [comment] 2018-08-07 05:43
This is the biggest problem of the project

**Comment by bard** [comment] 2019-04-10 08:21
I had documents containing html like `<pre>&lt;span&gt;a = 1&lt;/span&gt;</pre>` (i.e. code samples of html itself) and wanted to process them with cheerio before displaying sending them to the browser. `decodeEntities: false` obviously was not working due to the problem reported in this issue, and `decodeEntities: true` was encoding far more than `<` and `>`.

I kept `decodeEntities: false` and used https://www.npmjs.com/package/patch-package to generate and automatically apply this patch to `dom-serializer` upon every install:

```diff
diff --git a/node_modules/dom-serializer/index.js b/node_modules/dom-serializer/index.js
index 4f41e8f..8f9f14f 100644
--- a/node_modules/dom-serializer/index.js
+++ b/node_modules/dom-serializer/index.js
@@ -136,6 +136,8 @@ function renderText(elem, opts) {
     data = entities.encodeXML(data);
   }
 
+  data = data.replace(/</g, '&lt;').replace(/>/g, '&gt;')
+  
   return data;
 }
 ```

Since that only affects text nodes, it should not mess with anything, but caveat emptor.

I wonder if the clean solution here is replacing that `encodeXML` with something more context-aware, i.e. encode depending on the document type and charset.

**Comment by AlynxZhou** [comment] 2019-05-19 03:41
This issue still exists now and I am crazy because I am building a static site generator with cheerio. This problem behaves in two ways:

- First I am using marked.js and it will encode symbols like `<` in code blocks (`<pre></pre>) into `&lt`, that's what expected. However, if I set `decodeEntities: false`, cheerio will replace `&lt` back with `<`, which is ridiculous!!! Why parser decode `&lt` into `<`? I think it should not change this.
- But if I set `decodeEntities: true`, all CJK chars will be replaced into HTML entities, which is hard to deal with because some JavaScript codes needs to get string length, HTML entities is OK to render but not easy to process.

Can anybody locate the problem and fix it? Thanks a lot.

**Comment by AlynxZhou** [comment] 2019-05-19 04:05
After read @bard 's comment, I think problem is `escape`, not `encode`, if we set `decodeEntities` to `false`, we mean that we don't need to encode entities when output strings, but we DO need to ESCAPE (`<` to `&lt`, `>` to `&gt`, `&` to `&amp`, only a few symbols), because cheerio un-escaped things like `&lt` when reading, maybe a side-effect of parser or other reasons, so we need to cancel it.

I believe escaping is easy to implement because it only has few symbols to escape, a function like `const escapeHTML = (str) => { return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;"); }` is enough.

Needs help because I am not so familiar to cheerio, in my condition it works but don't know others.

**Comment by AlynxZhou** [comment] 2019-05-19 04:34
I solved it by changing following:

First add `escapeHTML()` into `dom-serializer`:

```javascript
function escapeHTML(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
```

Then modified `renderText()`, you can read comment for reason:

```javascript
function renderText(elem, opts) {
  var data = elem.data || '';

  if (!(elem.parent && elem.parent.name in unencodedElements)) {
    // When cheerio reading (decoding) input, it will unescape symbols
    // like `&lt` to `<` in innerHTML, no matter whether `decodeEntities`
    // is `true` or `false`.
    if (opts.decodeEntities) {
      // `entities.encodeXML()` will do escape so we won't to escape.
      data = entities.encodeXML(data);
    } else {
      // We need to escape by ourselves.
      data = escapeHTML(data)
    }
  }

  return data;
}
```

And I got what I want in test:

![Screenshot from 2019-05-19 12-28-51](https://user-images.githubusercontent.com/8444615/57977743-b038a800-7a31-11e9-8067-3112938ebc6f.png)

If OK, I will send a PR to `dom-serializer`.

**Comment by AlynxZhou** [comment] 2019-05-19 07:11
After reading codes for 3 hours I believe I find where problem begins.

@bard I think your patch is not correct, not only innerHTMLs but attrs also has this problem.

The problem is because cheerio is switching from `htmlparser2` to `parse5`, and `decodeEntities` is an option to `htmlparser2`, but not an option to `parse5`, in version `1.0.0-rc3`, they did not pass this option to `parse5` too.

If we use `htmlparser2` with `decodeEntities: false`, all things works correctly. However if you install cheerio with `npm i -s cheerio`, you got `1.0.0-rc3`, which uses `parse5`.

`parse5` will parse `&lt;` into `<` when it reading input, while `htmparser2` with `decodeEntities: false` won't. And when we get result with `.html()`, `cheerio` will use `dom-serializer` to render strings.

`dom-serializer` supposes parser understanding `decodeEntities`, suppose we have `&lt;` as input, if `decodeEntities` is true, `dom-serializer` should get `&`, else it should get `<`. When we are using `htmlparser2`, it works. With `decodeEntities: false`, it looks like `&lt;`(input) -> `&lt;`(parsed) -> `&lt;`(before and after serialized). With `decodeEntities: true`, it looks like `&lt;`(input) -> `<`(parsed) -> `<`(before serialized) -> `&lt;` (after serialized).

But whether `decodeEntities` is true or not, `parse5` always parse `&lt;` into `<`, if we set it to true, it looks like `&lt;`(input) -> `<`(parsed) -> `<`(before serialized) -> `&lt;` (after serialized), however, chars like Chinese and Japanese are ALSO encoded, which is BAD. But if we set it to false, it looks like `&lt;`(input) -> `<`(parsed) -> `<`(before serialized) -> `<` (after serialized because `decodeEntities` is false), which is totally a mess.

`dom-serializer` is right, it has no fault in its behavior. There are two ways to fix:
- Stop use `parse5`, let us use `htmlparser2` again by install `0.22.0` with `npm i -s cheerio@0.22.0` (code in master branch is still `0.22.0`, confusing). @fb55 @jugglinmike @matthewmueller 
- Make `parse5` able to understand `decodeEntites`, because sometimes we want to keep `&lt;` or `&amp;` in innerHTML, always un-escape them will cause a mess. @inikulin 

We'd better not modify `dom-serializer`, because it's a `parse5` issue. `parse5` does NOT always un-escape `&amp;`, it replace `&amp` in innerHTML into `&`, but won't replace `&amp;` in attributes.

It's a little bit long because it's complex, but please read and fix it, we cannot always lock version to `0.22.0`.

**Comment by bard** [comment] 2019-05-19 07:58
Based on https://github.com/jsdom/jsdom/issues/2501 and https://github.com/inikulin/parse5/issues/261#issuecomment-401389295 it's unlikely that this will be handled in `parse5`.

The second thread suggests that it's possible to grab the raw, undecoded text from the input data based on node position, though that would require modifying dom-serializer, too.

**Comment by AlynxZhou** [comment] 2019-05-19 08:15
@bard `dom-serializer` is used to generate strings from dom, not dom from string. We shouldn't touch it because it works correctly.

**Comment by AlynxZhou** [comment] 2019-05-19 08:39
@bard we can modify `dom-serializer` to prevent this bug, but must assume dom is generated with `parse5`, which needs more code for handling `xmlMode` (use `htmlparse2`), and this will make options unclear...

**Comment by AlynxZhou** [comment] 2019-05-19 08:48
due to <https://github.com/inikulin/parse5/issues/75> we know `parse5` always decode entities, so `decodeEntites` is useless, and then we should add another option for encode entities or not, problems are cheerio currently support both `parse5`(for HTML) and `htmlparser2`(for XML)...

**Comment by propattern** [comment] 2019-06-03 00:54
Thanks @AlynxZhou.  Great find.  Your 1st Solution worked for me, but you are right that we can't be permanently be bound to version 0.22.0.

**Comment by AlynxZhou** [comment] 2019-06-03 01:12
I send a PR to dom-serializer to fix 1.0.0, however no one replied...

**Comment by matthewmueller** [comment] 2019-06-03 03:50
@fb55 @jugglinmike this seems to be causing some folks pain. If i recall, we were going to continue supporting both `dom-serializer` and `parse5`. do we have a snippet that we can point people to for the old behavior?

**Comment by AlynxZhou** [comment] 2019-06-03 05:31
This is because parse5 ignores decodeEntity, I modified dom-serializer to fix this, but it needs a version bump.

**Comment by inikulin** [comment] 2019-06-27 18:33
I wonder what breaks exactly with decoded entities. The only thing that comes to my mind is that resulting pages are served in encoding other than UTF-8. Otherwise, nowadays there is no reason to prefer HTML entities (with an exception for safety-related HTML escaping) over code points.

**Comment by fb55** [comment] 2019-06-27 18:51
@inikulin The issue is serialization. Some people have entities as plain text in their HTML or want to maintain the encoding style they've used.

**Comment by AlynxZhou** [comment] 2019-07-02 03:56
@fb55 But for people who don't want HTML entities in their files, cheerio 1.0.0 is totally broken because it cannot handle things correctly (decodeEntities false, `&lt;` becomes `<`, decodeEntities true, CJK chars becomes entities). The problem is not in cheerio, it's because parse5 always decode entities while parsing. Using `decodeEntities` to decide whether we should encode is not a good choice, because we cannot control whether decode entities when using parse5, we'd better not to encode entities, just escape HTML is enough. cheerio is expected to be a parser, not encoder, encoding all entities makes it really hard for further string editing.

I hope you can consider my PR <https://github.com/cheeriojs/dom-serializer/pull/80>, I am using cheerio in my tools and I cannot always stick to 0.22.0.

**Comment by AlynxZhou** [comment] 2019-08-07 06:33
One month passed and this problem still exists:

![Screenshot from 2019-08-07 14-30-46](https://user-images.githubusercontent.com/8444615/62599881-02e27b80-b920-11e9-9b44-8ceadb07249e.png)

I am afraid that as a Chinese user I have to keep using cheerio 0.22.0 in my project forever because it seems no one will take a look on the reason I found.

**Comment by claviska** [comment] 2019-08-07 13:52
@AlynxZhou [this workaround](https://github.com/cheeriojs/cheerio/issues/866#issuecomment-482730997) should help. I've been using it in production since April with no ill effects.

**Comment by AlynxZhou** [comment] 2019-08-08 01:34
@claviska Thank you. But what I want is not a workaround, I know I can solve it by a simple hook. However, the problem is a bug in fact, it is because new library's behavior is different from the old one, and it needs to be fixed by remove unsupported option, it's complex and needs a change of logic, workaround can only hide the problem, but the problem still exists and may break other part.

Anyway thank you for your help.

**Comment by claviska** [comment] 2019-08-08 14:24
@AlynxZhou I'd like to see it fixed too, but this is open source so our options are to:

1. Contribute a fix
2. Use a workaround 
3. Wait patiently
4. Use an old version that probably won't get updated 😕

What I've proposed can be used as a separate module that you can easily remove once the bug is properly fixed. If you want to use the latest version without this encoding issue, it's probably your best bet.

Cheers

**Comment by AlynxZhou** [comment] 2019-08-09 03:21
@claviska I have send a PR to dom-serializer which removed decodeEntities because parser5 always do decoding and this options is useless. However, still no one replied.

**Comment by matthewmueller** [comment] 2019-08-18 16:23
To unblock, you can use the old parser:

```js
const cheerio = require('cheerio')
const $ = cheerio.load(`<code>&lt;script src&gt;</code>`, {
  _useHtmlParser2: true,
  decodeEntities: false,
})
console.log($.html())
```

This is undocumented and may be removed when we go to 1.0.0. I hope this is okay, @jugglinmike @fb55. 

@AlynxZhou thanks for taking the time to share your findings. Unfortunately, it's not easy for me to tell if this solves your problem or not. Can you please reframe your problem in the following way:

1. Create a minimal code example that illustrates the problem.
2. What you expect to see.
3. What you actually see.

This will help us debug your issue. You can refer to the original poster for a decent example of this.

**Comment by AlynxZhou** [comment] 2019-08-19 01:45
@matthewmueller No need to check via code, I can tell you this can definitely solve problem, however, as you said, `_useHtmlParser2` is undocumented and may be removed, so I am afraid that I can't use such a unstable feature in my project to fix bugs.

Such snippet is just let 1.0.0 works like 0.22.0, to solve problem we need to consider differences between parse5 and htmlparser2, and I need to say again, encode all things into XML entities is a **BAD** option and we may consider to drop it because parse5 always decode input.

**Comment by matthewmueller** [comment] 2019-08-19 09:27
It's highly dependent on your use case, which is why we need to provide an option to switch. parse5 is a better supported parser at this point and I believe it was @fb55's idea to switch to it over his own parser. 

FYI, for the final public API I'd probably try and have a parser interface like this:

```
const parser = {
  parse(code: string): AST
}

cheerio.load("...", { parser: parser })
```

What do you think @jugglinmike @fb55 ?

**Comment by AlynxZhou** [comment] 2019-08-19 09:36
> It's highly dependent on your use case, which is why we need to provide an option to switch. parse5 is a better supported parser at this point and I believe it was @fb55's idea to switch to it over his own parser.

No, it's because currently `dom-serializer` has problem with parse5, I think we need to fix this, instead of let user switch to htmlparser2 simply.

> 
> FYI, for the final public API I'd probably try and have a parser interface like this:
> 
> ```ts
> const parser = {
>   parse(code: string): AST
> }
> 
> cheerio.load("...", { parser: parser })
> ```
> 
> What do you think @jugglinmike @fb55 ?

This did nothing for this problem now...difference is parse5 always decode contents, while htmlparser2 won't if you set `decodeEntities: false`...

Because parse5 always decode contents, if we set `decodeEntities: true`, `dom-serializer` will re-encode all things into XML entities, so the problem of `&gt;` goes away but Chinese character becomes XML entities. But it we set `decodeEntites: false`, `&gt;` becomes `>`, and `dom-serializer` won't re-encode it, which caused a bug. Problems exist in codes, not dependent my use case in fact.

You may read code and my PR in <https://github.com/cheeriojs/dom-serializer/pull/85> to get clear about it. Thank you.

**Comment by AlynxZhou** [comment] 2019-08-19 09:54
@matthewmueller Sorry, I am reading code again now and find that the problem has been fixed by using parse5's serializer instead of dom-serializer, so I am trying to test it, I am REALLY happy to see that it may be fixed!

**Comment by curbengh** [comment] 2019-08-19 11:17
So, https://github.com/cheeriojs/cheerio/pull/1307 fixed this issue?

**Comment by AlynxZhou** [comment] 2019-08-19 11:32
> So, #1307 fixed this issue?

I think it was fixed before this, you may do a test.

**Comment by curbengh** [comment] 2019-08-20 02:02
I previously had an issue with embedding xml code block in my blog. I can confirm it's fixed when I use [v1.0.0](https://github.com/cheeriojs/cheerio/tree/v1.0.0) branch.

OP @huanz can you confirm?

**Comment by AlynxZhou** [comment] 2019-09-26 09:06
@matthewmueller  Any plan for releasing 1.0.0? Or could you please consider to release another rc version to fix this problem? We really want 1.0.0 branch because it fixed this bug. Thanks!

**Comment by michaelperrin** [comment] 2020-08-01 22:20
I can confirm that the problem is fixed on the 1.0.0 branch 👍 I installed it this way:

    yarn add https://github.com/cheeriojs/cheerio.git#1.0.0

This is not ideal and hope that a new RC will soon be released.

**Comment by superhuai** [comment] 2020-12-06 10:23
is be fixed ？ I also have this problem

```
const $ = cheerio.load('<p>&lt;哈哈哈</p>')

console.log($('body').html())
```

```
npm i cheerio@1.0.0-rc.3
```

**Comment by AlynxZhou** [comment] 2020-12-07 00:56
> is be fixed ？ I also have this problem
> 
> ```
> const $ = cheerio.load('<p>&lt;哈哈哈</p>')
> 
> console.log($('body').html())
> ```
> 
> ```
> npm i cheerio@1.0.0-rc.3
> ```
> 
> emmm , it's ok
> 
> ```
> yarn add https://github.com/cheeriojs/cheerio.git#1.0.0
> ```

two years past and they still don't update version on npm, so you will still face this problem if you install 1.0.0-rc3 from npm. You need to install 1.0.0 branch from github.

**Comment by fb55** [comment] 2020-12-21 22:30
`cheerio@1.0.0-rc.5` is now on npm. Hoping this is resolved now!

**Closed by fb55** 2020-12-21 22:30 UTC

**Comment by magicdawn** [comment] 2023-04-26 12:12
looks like for xhtml output + cjk charaters, `_useHtmlParser2` is still needed.


```ts
import { load } from 'cheerio'

const html = `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <br />
    <pre>
      // 哈哈哈
      // swift generic
      var a5 = MemoryLayout&lt;UInt&gt;.size
    </pre>
  </body>
</html>

`

console.log('-'.repeat(20))
{
  const $ = load(html, {})
  const y = $.xml().trim()
  console.log(y)
  // &#x54c8;&#x54c8;&#x54c8;                    <--------- wrong, so `decodeEntities` is needed
  // swift generic
  // var a5 = MemoryLayout&lt;UInt&gt;.size
}

console.log('-'.repeat(20))
{
  const $ = load(html, {
    decodeEntities: false,
  })
  const y = $.xml().trim()
  console.log(y)
  // 哈哈哈                                      <--------- correct
  // swift generic
  // var a5 = MemoryLayout<UInt>.size           <--------- wrong, it's code in a `<pre>` tag
}

console.log('-'.repeat(20))
{
  const $ = load(html, {
    // @ts-ignore
    _useHtmlParser2: true,
    decodeEntities: false,
  })
  const y = $.xml().trim()
  console.log(y)
  // 哈哈哈                                      <--------- correct
  // swift generic
  // var a5 = MemoryLayout&lt;UInt&gt;.size     <--------- correct
}

```
