### ISSUE TITLE
It's not possible to import "cheerio/lib/utils" anymore

### ISSUE THREAD

**Issue by blixt** [cheeriojs/cheerio#2600] opened 2022-06-17 18:46 UTC
Enzyme has this import which now fails:
https://github.com/enzymejs/enzyme/blob/master/packages/enzyme/src/Utils.js#L11

**Comment by fb55** [comment] 2022-06-26 10:03
Duplicate of #2547

**Closed by fb55** 2022-06-26 10:03 UTC
