### ISSUE TITLE
Why does the installation gets stuck phantomjs module?

### ISSUE THREAD

**Issue by Itagiba** [cheeriojs/cheerio#847] opened 2016-04-09 21:43 UTC
I am trying to get cheerio running with `sudo npm install request cheerio`, the whole thing seems to work then gets stuck at 99% in the following step:

```
Received 17340K total.
Extracting zip contents
Removing /Users/parazj/git/node_modules/phantomjs2.0/lib/phantom
Copying extracted folder /Users/parazj/git/node_modules/phantomjs2.0/phantomjs/phantomjs-2.0.0-20150731-macosx.zip-extract-1460237379863/phantomjs-2.0.0-20141016 -> /Users/parazj/git/node_modules/phantomjs2.0/lib/phantom
```

Why would this be happening?

**Comment by luanmuniz** [comment] 2016-04-09 23:31
I cant reproduce it. I've tried `sudo npm install request` and `sudo npm install cheerio` and both together and i cant reproduce this.

I also search for any reference of phantomjs inside `cheerio` and all dependences. This was the result:
```
Searching 2628 files for "phantomjs"

/cheerio/node_modules/jsdom/node_modules/escodegen/node_modules/.bin/esvalidate:
   30  
   31  if (typeof esprima === 'undefined') {
   32:     // PhantomJS can only require() relative files
   33      if (typeof phantom === 'object') {
   34          fs = require('fs');
   ..
   47  }
   48  
   49: // Shims to Node.js objects when running under PhantomJS 1.7+.
   50  if (typeof phantom === 'object') {
   51      fs.readFileSync = fs.read;
   ..
   54          exit: phantom.exit
   55      };
   56:     process.argv.unshift('phantomjs');
   57  }
   58  

/cheerio/node_modules/jsdom/node_modules/escodegen/node_modules/esprima/bin/esvalidate.js:
   30  
   31  if (typeof esprima === 'undefined') {
   32:     // PhantomJS can only require() relative files
   33      if (typeof phantom === 'object') {
   34          fs = require('fs');
   ..
   47  }
   48  
   49: // Shims to Node.js objects when running under PhantomJS 1.7+.
   50  if (typeof phantom === 'object') {
   51      fs.readFileSync = fs.read;
   ..
   54          exit: phantom.exit
   55      };
   56:     process.argv.unshift('phantomjs');
   57  }
   58  

/cheerio/node_modules/jsdom/node_modules/request/node_modules/node-uuid/README.md:
  232  
  233  * Properly detect node crypto and whatwg crypto
  234: * Workaround phantomjs/browserify bug
  235  * Explicit check for `window` rather implicit this-global
  236  * Issue warning if Math.random() is being used

/cheerio/node_modules/jsdom/node_modules/request/package.json:
   69      "karma-cli": "^0.1.1",
   70      "karma-coverage": "^0.5.3",
   71:     "karma-phantomjs-launcher": "^1.0.0",
   72      "karma-tap": "^1.0.3",
   73:     "phantomjs-prebuilt": "^2.1.3",
   74      "rimraf": "^2.2.8",
   75      "server-destroy": "^1.0.1",

/cheerio/node_modules/lodash/core.js:
 2765      // The use of `Object#toString` avoids issues with the `typeof` operator
 2766      // in Safari 8 which returns 'object' for typed array and weak map constructors,
 2767:     // and PhantomJS 1.9 which returns 'function' for `NodeList` instances.
 2768      var tag = isObject(value) ? objectToString.call(value) : '';
 2769      return tag == funcTag || tag == genTag;

/cheerio/node_modules/lodash/isFunction.js:
   36    // The use of `Object#toString` avoids issues with the `typeof` operator
   37    // in Safari 8 which returns 'object' for typed array and weak map constructors,
   38:   // and PhantomJS 1.9 which returns 'function' for `NodeList` instances.
   39    var tag = isObject(value) ? objectToString.call(value) : '';
   40    return tag == funcTag || tag == genTag;

/cheerio/node_modules/lodash/lodash.js:
 10639        // The use of `Object#toString` avoids issues with the `typeof` operator
 10640        // in Safari 8 which returns 'object' for typed array and weak map constructors,
 10641:       // and PhantomJS 1.9 which returns 'function' for `NodeList` instances.
 10642        var tag = isObject(value) ? objectToString.call(value) : '';
 10643        return tag == funcTag || tag == genTag;

/cheerio/node_modules/lodash/README.md:
   37  ## Support
   38  
   39: Tested in Chrome 48-49, Firefox 44-45, IE 9-11, Edge 13, Safari 8-9, Node.js 0.10, 0.12, 4, & 5, & PhantomJS 1.9.8.<br>
   40  Automated [browser](https://saucelabs.com/u/lodash) & [CI](https://travis-ci.org/lodash/lodash/) test runs are available.
   41  
```

Looking at this i can conclude a few things.
1. The problem is not inside the cheerio repository
2. If the problem is inside a cheerio dependence, its more probable `esprima` (`cheerio -> jsdom -> escodegen -> esprima`)
3. I can't find anything that download or extract phantomjs in any dep or dep of dep
4. Considering all these information, the problem is more probably in another part of your stack.

I don't know if this help, but if you are still thinking that the problem is in `cheerio`, can you give more information about how to reproduce this?

**Comment by kiwiheretic** [comment] 2017-01-13 01:13
I'm also not getting cheerio working inside PhantomJS 2.1.  Does this have a fix yet?  It appeared to load after using browserify  ( https://github.com/cheeriojs/cheerio/issues/841 ) but it wont actually parse any html, even the example, without errors.  Here is my simple test code.

```
var port, server, service,
    system = require('system'),
    fs = require('fs'),
    page = require('webpage').create(),
    cheerio = require('./cheerio.js'),
    optparse = require('./optparse-js/lib/optparse.js'),
    sprintfjs = require('./sprintf.js/src/sprintf.js'),
    sprintf = sprintfjs.sprintf,
    utils = require('./util-fns');

var s = ' \
<ul id="fruits"> \
  <li class="apple">Apple</li> \
  <li class="orange">Orange</li> \
  <li class="pear">Pear</li> \
</ul> ';
console.log(s);
var $ = cheerio.load(s);
phantom.exit();
```

**Comment by fb55** [comment] 2017-01-13 12:20
@kiwiheretic I think you need to supply an option to browserify to get something that can be required as a module (otherwise its a self-contained JS file).

As far as the original issue is concerned, I would guess that @Itagiba also has phantomjs in his `package.json`, which fails to install for some reason. As this was several months ago, I'm closing this.

**Closed by fb55** 2017-01-13 12:20 UTC

**Comment by kiwiheretic** [comment] 2017-01-15 21:19
Well I followed the instructions on the browserify website.  So unless cheerio has something different in its requirements that affect the use of browserify....

Currently there seems no workaround for this so I've gone back to putting phantomjs behind a django front end and using python BeautifulSoup to parse the html.  It seems that phantomjs just doesn't support cheerio and it seems that Cheerio requires the use of modules not available in phantomjs (unless someone can show me a working example to the contrary).
