### ISSUE TITLE
Sibling selector not selecting root elements

### ISSUE THREAD

**Issue by apaleslimghost** [cheeriojs/cheerio#890] opened 2016-07-07 14:39 UTC
Trying to select from multiple root elements with the sibling selector doesn't select anything, e.g.:

``` js
$ = cheerio.load('<p>1</p><p>2</p><p>3</p><p>4</p>');
$2 = cheerio.load('<div><p>1</p><p>2</p><p>3</p><p>4</p></div>');

$('p').length //⇒ 4
$('p + p').length //⇒ 0 (huh?)
$2('p + p').length //⇒ 3
```

https://tonicdev.com/quarterto/577e6819f832ee13002f0a5a

**Comment by MCTaylor17** [comment] 2016-07-07 21:45
I just ran into this problem myself.  I thought I was going crazy because I know that I've used adjacent sibling selectors before.

**Comment by Gei0r** [comment] 2018-11-24 18:07
The problem is still active, here's a different way of triggering it:

    var cheerio = require("cheerio")
    
    let $ = cheerio.load(`
    <a>
      <b/>
      <c/>
    </a>
    <d/>`, {xmlMode: true});
    
    console.log("b has " + $('b').siblings().length + " siblings");
    console.log("d has " + $('d').siblings().length + " siblings");

Output:

    b has 1 siblings
    d has 0 siblings

https://runkit.com/embed/x6aemslp98hd

**Comment by MCTaylor17** [comment] 2018-11-29 23:30
If it's not obvious, the workaround is simply to wrap the contents in a temporary tag.  I would load HTML with a `<temp>` wrapper and save my outputs with `$("temp").html()` rather than the usual `$.html()`.

**Comment by fb55** [comment] 2020-12-22 18:30
This was fixed with the latest release!

**Closed by fb55** 2020-12-22 18:30 UTC
